=== skyvers/skyve/skyve-core/src/test/resources/schemas/router.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://www.skyve.org/xml/router" xmlns:tns="http://www.skyve.org/xml/router" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.skyve.org/xml/common">

  <xs:import namespace="http://www.skyve.org/xml/common" schemaLocation="common.xsd"/>

  <xs:element name="route" type="tns:route"/>

  <xs:element name="router" type="tns:router"/>

  <xs:complexType name="router">
    <xs:sequence>
      <xs:element name="uxui" type="tns:uxUiMetadata" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="direct" type="tns:direct" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="unsecured" type="xs:string" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="properties" type="ns1:propertyMapType" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="uxuiSelectorClassName" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="uxUiMetadata">
    <xs:complexContent>
      <xs:extension base="ns1:namedMetaData">
        <xs:sequence>
          <xs:element ref="tns:route" maxOccurs="unbounded"/>
          <xs:element name="properties" type="ns1:propertyMapType" form="qualified" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="route">
    <xs:sequence>
      <xs:element name="criteria" type="tns:routeCriteria" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="properties" type="ns1:propertyMapType" form="qualified" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="outcome" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="routeCriteria">
    <xs:sequence/>
    <xs:attribute name="customer" type="xs:string"/>
    <xs:attribute name="dataGroupId" type="xs:string"/>
    <xs:attribute name="document" type="xs:string"/>
    <xs:attribute name="module" type="xs:string"/>
    <xs:attribute name="query" type="xs:string"/>
    <xs:attribute name="userId" type="xs:string"/>
    <xs:attribute name="viewType" type="ns1:viewType"/>
    <xs:attribute name="webAction" type="ns1:webAction"/>
  </xs:complexType>

  <xs:complexType name="direct">
    <xs:sequence/>
    <xs:attribute name="match" type="tns:directMatch"/>
    <xs:attribute name="path" type="xs:string" use="required"/>
    <xs:attribute name="userAgentType" type="ns1:userAgentType"/>
    <xs:attribute name="uxui" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="directMatch">
    <xs:restriction base="xs:string">
      <xs:enumeration value="exact"/>
      <xs:enumeration value="prefix"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== skyvers/skyve/wildcat-ee/src/skyve/router/router.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<router uxuiSelectorClassName="router.DefaultUxUiSelector"
			xmlns="http://www.skyve.org/xml/router"
			xsi:schemaLocation="http://www.skyve.org/xml/router ../schemas/router.xsd"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<uxui name="desktop">
		<route outcome="/desktop/home.xhtml" />
	</uxui>
	<uxui name="public">
		<route outcome="/public/grid.xhtml">
			<criteria webAction="g" />
		</route>
		<route outcome="/public/edit.xhtml">
			<criteria webAction="e" />
		</route>
		<route outcome="/public/calendar.xhtml">
			<criteria webAction="c" />
		</route>
		<route outcome="/public/map.xhtml">
			<criteria webAction="m" />
		</route>
		<route outcome="/public/tree.xhtml">
			<criteria webAction="t" />
		</route>
		<route outcome="/public/frameset.xhtml" />
	</uxui>
	<uxui name="tablet">
		<route outcome="/tablet/grid.xhtml">
			<criteria webAction="g" />
		</route>
		<route outcome="/tablet/edit.xhtml">
			<criteria webAction="e" />
		</route>
		<route outcome="/tablet/calendar.xhtml">
			<criteria webAction="c" />
		</route>
		<route outcome="/tablet/map.xhtml">
			<criteria webAction="m" />
		</route>
		<route outcome="/tablet/tree.xhtml">
			<criteria webAction="t" />
		</route>
		<route outcome="/tablet/frameset.xhtml" />
	</uxui>
	<uxui name="phone">
		<route outcome="/whosinIntegrate/inout.xhtml">
			<criteria webAction="e" module="whosinIntegrate" document="Office" />
		</route>
		<route outcome="/phone/grid.xhtml">
			<criteria webAction="g" />
		</route>
		<route outcome="/phone/edit.xhtml">
			<criteria webAction="e" />
		</route>
		<route outcome="/phone/menu.xhtml" />
	</uxui>
</router>
